version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: springbatch-postgres
    environment:
      POSTGRES_DB: springbatchdb
      POSTGRES_USER: springbatchuser
      POSTGRES_PASSWORD: springbatchpassword
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d